# Generated by Django 3.2.3 on 2021-08-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('waktu', models.DateTimeField()),
                ('pengguna', models.CharField(max_length=50)),
            ],
        ),
    ]
